language: node_js
sudo: true
dist: trusty
addons:
  code_climate:
    repo_token: 28678b9f6635277f6fab20206fa4cf8c9168103ec257b5eb09c42b5322d807c1
node_js:
- 6.9.5
after_success:
- npm install -g codeclimate-test-reporter
- codeclimate-test-reporter < coverage/lcov.info
- npm run semantic-release
- npm run deploy-storybook
cache:
  yarn: true
  directories:
    - node_modules
branches:
  only:
    - master
before_install:
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
before_script:
- yarn
script: yarn test -- --coverage
